DATASET:
  root_dataset: "/Data/dataLIDAR/0221-1730_seed_9876/clear_day/"
  list_train: "./data/clear/odgt/train.odgt"
  list_val: "./data/clear/odgt/validate.odgt"
  num_class: 29
  imgSizes: (360, 540, 720)  # Smaller sizes
  imgMaxSize: 960
  padding_constant: 32
  segm_downsampling_rate: 4
  random_flip: True

MODEL:
  arch_encoder: "hrnetv2"
  arch_decoder: "c3"
  fc_dim: 720

TRAIN:
  batch_size_per_gpu: 1
  num_epoch: 960
  start_epoch: 10
  epoch_iters: 960
  optim: "SGD"
  lr_encoder: 0.02
  lr_decoder: 0.02
  lr_pow: 0.9
  beta1: 0.9
  weight_decay: 1e-4
  deep_sup_scale: 0.4
  fix_bn: False
  workers: 16
  disp_iter: 20
  seed: 304
  freeze_depth: True
  freeze_rgb: True

VAL:
  visualize: True
  checkpoint: "epoch_19.pth"

TEST:
  checkpoint: "epoch_19.pth"
  result: "./"

DIR: "/Data/fusion/ckpt/surgery_3"